import turtle as t
# 길이가 200인 정사각형 노란 몸체 만들기
t.up()
t.goto(-100, 0)
t.down()
t.fillcolor("yellow")
t.begin_fill()
t.forward(200)
t.left(90)
t.forward(200)
t.left(90)
t.forward(200)
t.left(90)
t.forward(200)
t.end_fill()
# 몸체 위에 초록색 삼각형 지붕 만들기
t.left(90)
t.up()
t.goto(-100, 200)
t.fillcolor("green")
t.begin_fill()
t.forward(200)
t.left(120)
t.forward(200)
t.left(120)
t.forward(200)
t.end_fill()
# 반지름이 30인 갈색 바퀴 만들기
t.left(120)
t.up()
t.goto(-50, -60)
t.down()
t.fillcolor("brown")
t.begin_fill()
t.circle(30)
t.end_fill()
t.up()
t.goto(50, -60)
t.down()
t.begin_fill()
t.circle(30)
t.end_fill()
t.done()
